
# Site settings
title: Kafka先生的生活奇点
email: themeiwu@hotmail.com
description: > # this means to ignore newlines until "baseurl"
  kafka先生的生活奇点 mr.kafka's singular point alpha实验室 alpha lab
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: themeiwu
email: themeiwu@hotmail.com
facebook_username: 
twitter_username: 
github_username:  Wuthemei
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:themeiwu.com

# API settings
google_api_key:

# Build settings
gems: [jekyll-paginate]

markdown: kramdown
# toc_levels: 1..2
gems: [jekyll-paginate]
paginate: 5
